removeSliderAt(position) function not work #88 and a NPE
1. fixed removeSliderAt(position) function not work #88
logic mistake.
2. NullPointerException in MainActivity.java
05-05 04:12:14.960      472-472/? E/AndroidRuntime﹕ FATAL EXCEPTION:
main
Process: com.daimajia.slider.demo, PID: 472
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.daimajia.slider.demo/com.daimajia.slider.demo.MainActivity}:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
android.os.Bundle.putString(java.lang.String, java.lang.String)' on a
null object reference
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
....
Caused by: java.lang.NullPointerException: Attempt to invoke virtual
method 'void android.os.Bundle.putString(java.lang.String,
java.lang.String)' on a null object reference
at com.daimajia.slider.demo.MainActivity.onCreate(MainActivity.java:57)
at android.app.Activity.performCreate(Activity.java:5933)
at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)